# asdf Erlang dependencies
brew "autoconf"
brew "openssl@1.1"
brew "wxwidgets"
brew "libxslt"
brew "fop"

# asdf NodeJS dependencies
brew "coreutils"
brew "gpg"

# Lua lsp
brew "lua-language-server"

# Vim dependencies
brew "neovim"
brew "tree-sitter", args: ["HEAD"]
brew "luajit", args: ["HEAD"]

# Miscellaneous goodies
brew "bat"
brew "glow"
brew "fish"
brew "peco"
brew "pillow"

# Casks
cask "hammerspoon"
cask "kitty"
