#!bin/bash

# Install asdf-vm
if [ ! -d "$HOME/.asdf" ]; then
	echo "Installing asdf-vm..."
	git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.9.0
fi

source $HOME/.asdf/asdf.sh
source $HOME/.asdf/completions/asdf.bash
