#!/bin/bash

fish=~/.config/fish/config.fish
fish_variables=~/.config/fish/fish_variables

# Fish
if [ ! -f $fish ] ; then
	echo "Creating symbolic link for config.fish..."
	mkdir -p ~/.config/fish
	ln -s $PWD/fish/config.fish $fish
fi
