#!/bin/bash

Brewfile=~/Brewfile

# Install
if ! command -v brew &> /dev/null
then
	echo "Installing Homebrew..."
	curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
fi

# Set up symlinks
if [ ! -f $Brewfile ] ; then
	echo "Creating symbolic link for Brewfile..."
	ln -s $PWD/homebrew/Brewfile $Brewfile
fi

# Install packages
echo "Installing Brewfile packages..."
brew bundle --file=$Brewfile
