#!/bin/bash

####################
####   NODEJS   ####
####################

nodejs_ver=lts

asdf plugin-add nodejs
asdf plugin-update nodejs
asdf install nodejs $nodejs_ver
asdf global nodejs $nodejs_ver

####################
####   ELIXIR   ####
####################

erlang_ver=25.1.2
elixir_ver=1.14.2-otp-25

echo "Installing erlang..."

# asdf-erlang
export KERL_CONFIGURE_OPTIONS="--without-javac --with-ssl=$(brew --prefix openssl@1.1)"
export KERL_BUILD_DOCS="yes"

asdf plugin-add erlang
asdf plugin-update erlang

asdf install erlang $erlang_ver
asdf global erlang $erlang_ver

echo "Installing elixir..."

# asdf-elixir
asdf plugin-add elixir
asdf plugin-update elixir
asdf install elixir $elixir_ver
asdf global elixir $elixir_ver

####################
####   GOLANG   ####
####################

golang_ver=1.19

# asdf-golang
echo "Installing golang..."
asdf plugin-add golang
asdf install golang $golang_ver
asdf global golang $golang_ver

#####################
####   CLEANUP   ####
#####################

echo "Reshimming asdf binaries..."
asdf reshim
