#!/bin/bash

lsp_root=~/.config/lsp
mkdir $lsp_root/.tmp


####################
####   ELIXIR   ####
####################

elixir_ls_dir=$lsp_root/elixir-ls
elixir_ls_ver=0.9.0

erlang_ver=24.2.1
elixir_ver=1.13.2-otp-24

echo "Installing elixir..."

# asdf-erlang
asdf plugin-add erlang
asdf install erlang $erlang_ver
asdf global erlang $erlang_ver

# asdf-elixir
asdf plugin-add elixir
asdf install elixir $elixir_ver
asdf global elixir $elixir_ver

# elixir-ls
echo "Downloading elixir-ls release..."
curl -L https://github.com/elixir-lsp/elixir-ls/releases/download/v$elixir_ls_ver/elixir-ls.zip -o $lsp_root/.tmp/elixir-ls.zip &> /dev/null

echo "Unzipping elixir-ls release into proper directory..."
unzip -o $lsp_root/.tmp/elixir-ls.zip -d $lsp_root/elixir-ls/ &> /dev/null

####################
####   GOLANG   ####
####################

golang_ver=1.17.6

# asdf-golang
echo "Installing golang..."
asdf plugin-add golang
asdf install golang $golang_ver
asdf global golang $golang_ver

# gopls
echo "Installing gopls..."
go install golang.org/x/tools/gopls@latest


#####################
####   CLEANUP   ####
#####################

echo "Reshimming asdf binaries..."
asdf reshim

echo "Removing temporary files..."
rm -rf $lsp_root/.tmp
