#!/bin/bash

lsp_root=~/.config/lsp
mkdir $lsp_root/.tmp

####################
####   NODEJS   ####
####################

nodejs_ver=lts

asdf plugin-add nodejs
asdf install nodejs $nodejs_ver
asdf global nodejs $nodejs_ver

# jsonls
npm i -g vscode-langservers-extracted

# tailwindcss-ls
npm i -g @tailwindcss/language-server

####################
####   ELIXIR   ####
####################

erlang_ver=25.0.4
elixir_ver=1.13.4-otp-25

elixir_ls_dir=$lsp_root/elixir-ls
elixir_ls_ver=0.11.0
elixir_ls_dbl=1.13-25.0

echo "Installing erlang..."

# asdf-erlang
export KERL_CONFIGURE_OPTIONS="--without-javac --with-ssl=$(brew --prefix openssl@1.1)"
asdf plugin-add erlang
asdf install erlang $erlang_ver
asdf global erlang $erlang_ver

echo "Installing elixir..."

# asdf-elixir
asdf plugin-add elixir
asdf install elixir $elixir_ver
asdf global elixir $elixir_ver

# elixir-ls
echo "Downloading elixir-ls release..."
curl -L https://github.com/elixir-lsp/elixir-ls/releases/download/v$elixir_ls_ver/elixir-ls-$elixir_ls_dbl.zip -o $lsp_root/.tmp/elixir-ls.zip &> /dev/null

echo "Unzipping elixir-ls release into proper directory..."
unzip -o $lsp_root/.tmp/elixir-ls.zip -d $lsp_root/elixir-ls/ &> /dev/null

####################
####   GOLANG   ####
####################

golang_ver=1.19

# asdf-golang
echo "Installing golang..."
asdf plugin-add golang
asdf install golang $golang_ver
asdf global golang $golang_ver

# gopls
echo "Installing gopls..."
go install golang.org/x/tools/gopls@latest


#####################
####   CLEANUP   ####
#####################

echo "Reshimming asdf binaries..."
asdf reshim

echo "Removing temporary files..."
rm -rf $lsp_root/.tmp
