#!bin/bash

bat=~/.config/bat/config
hammerspoon=~/.hammerspoon/init.lua
kitty=~/.config/kitty/kitty.conf
tmux_conf=~/.tmux.conf

# BAT
if [ ! -f $bat ] ; then
	echo "Creating symbolic link for BAT config..."
	ln -s $PWD/bat/config $bat
fi

# Hammerspoon
if [ ! -f $hammerspoon ] ; then
	echo "Creating symbolic link for Hammerspoon config..."
	ln -s $PWD/hammerspoon/init.lua $hammerspoon
fi

# Kitty
if [ ! -f $kitty ] ; then
	echo "Creating symbolic link for kitty config..."
	mkdir -p ~/.config/kitty
	ln -s $PWD/kitty/kitty.conf $kitty
fi

# Tmux
if [ ! -f $tmux_conf ] ; then
	echo "Creating symbolic link for tmux config..."
	ln -s $PWD/tmux/tmux.conf $tmux_conf
fi
